[package]
name = "example_rust_project"
version = "0.1.0"
edition = "2021"

[lib]
# tells rust to compile as a dynamic library which can be used by android
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"
#[target.'cfg(target_os = "android")'.dependencies]
#jni = "0.5"
